// locales.go

package i18n

import "fyne.io/fyne/v2"

var resourceRuYaml = &fyne.StaticResource{
	StaticName: "ru.yaml",
	StaticContent: []byte(
		"Password_Manager: { other: \"Менеджер паролей\" }\nUnlock_Password_Manager: { other: \"Разблокировать менеджер паролей\" }\nEnter_master_password: { other: \"Введите мастер-пароль\" }\ninvalid_master_password: { other: \"Неверный мастер-пароль\" }\nCreate_Master_Password: { other: \"Создать мастер-пароль\" }\nEnter_your_email: { other: \"Введите ваш email\" }\nConfirm_master_password: { other: \"Подтвердите мастер-пароль\" }\nSave: { other: \"Сохранить\" }\nSuccess: { other: \"Успех\" }\nMaster_password_saved: { other: \"Мастер-пароль сохранён\" }\npasswords_do_not_match: { other: \"Пароли не совпадают\" }\nemail_and_password_required: { other: \"Требуются email и пароль\" }\nFirst-time_setup: { other: \"Первичная настройка\" }\n\nSession_locked: { other: \"Сессия заблокирована из-за бездействия\" }\nMaster_Password: { other: \"Мастер-пароль\" }\nUnlock_Session: { other: \"Разблокировать сессию\" }\nUnlock: { other: \"Разблокировать\" }\nExit: { other: \"Выход\" }\n\nShow_Filters: { other: \"Показать фильтры\" }\nService: { other: \"Сервис\" }\nUsername: { other: \"Имя пользователя\" }\nCategory: { other: \"Категория\" }\nApply: { other: \"Применить\" }\nFilter_Passwords: { other: \"Фильтр паролей\" }\nClose: { other: \"Закрыть\" }\nRefresh: { other: \"Обновить\" }\n\nID: { other: \"ID\" }\nCreated_At: { other: \"Создано\" }\nLink: { other: \"Ссылка\" }\nCopy: { other: \"Копировать\" }\nLink_copied: { other: \"Ссылка скопирована в буфер обмена\" }\nPassword_copied: { other: \"Пароль скопирован в буфер обмена\" }\n\nActions: { other: \"Действия\" }\nAdd: { other: \"Добавить\" }\nUpdate: { other: \"Обновить\" }\nDelete: { other: \"Удалить\" }\nYour_Passwords: { other: \"Ваши пароли\" }\n\nCreate_Password: { other: \"Создать пароль\" }\nPassword: { other: \"Пароль\" }\nLength: { other: \"Длина\" }\nExclude: { other: \"Исключить\" }\nExclude_chars: { other: \"Исключить символы\" }\nGenerate: { other: \"Сгенерировать\" }\nInvalid_length: { other: \"Некорректная длина\" }\nGeneration_error: { other: \"Ошибка генерации\" }\nGenerated_inserted: { other: \"Сгенерированный пароль вставлен\" }\n\nWeak_password: { other: \"Слабый пароль\" }\nStrong_password: { other: \"Надёжный пароль\" }\nChoose_stronger: { other: \"Пожалуйста, выберите более надёжный пароль\" }\nmissing: { other: \"отсутствует\" }\nlength_8: { other: \"длина ≥ 8\" }\ndigit: { other: \"цифра\" }\nuppercase: { other: \"прописная буква\" }\nlowercase: { other: \"строчная буква\" }\nsymbol: { other: \"символ\" }\n\nUpdate_Password: { other: \"Обновить пароль\" }\nUpdated: { other: \"Обновлено\" }\nPassword_updated: { other: \"Пароль успешно обновлён\" }\n\nDelete_Password: { other: \"Удалить пароль\" }\nEnter_ID_to_delete: { other: \"Введите ID для удаления\" }\nDeleted: { other: \"Удалено\" }\nPassword_deleted: { other: \"Пароль успешно удалён\" }\nDB_init_failed: { other: \"Ошибка инициализации базы данных\" }"),
}
var resourceEnYaml = &fyne.StaticResource{
	StaticName: "en.yaml",
	StaticContent: []byte(
		"Password_Manager: { other: \"Password Manager\" }\nUnlock_Password_Manager: { other: \"Unlock Password Manager\" }\nEnter_master_password: { other: \"Enter master password\" }\ninvalid_master_password: { other: \"Invalid master password\" }\nCreate_Master_Password: { other: \"Create Master Password\" }\nEnter_your_email: { other: \"Enter your email\" }\nConfirm_master_password: { other: \"Confirm master password\" }\nSave: { other: \"Save\" }\nSuccess: { other: \"Success\" }\nMaster_password_saved: { other: \"Master password saved\" }\npasswords_do_not_match: { other: \"Passwords do not match\" }\nemail_and_password_required: { other: \"Email and password are required\" }\nFirst-time_setup: { other: \"First-time setup\" }\n\nSession_locked: { other: \"Session locked due to inactivity\" }\nMaster_Password: { other: \"Master Password\" }\nUnlock_Session: { other: \"Unlock Session\" }\nUnlock: { other: \"Unlock\" }\nExit: { other: \"Exit\" }\n\nShow_Filters: { other: \"Show Filters\" }\nService: { other: \"Service\" }\nUsername: { other: \"Username\" }\nCategory: { other: \"Category\" }\nApply: { other: \"Apply\" }\nFilter_Passwords: { other: \"Filter Passwords\" }\nClose: { other: \"Close\" }\nRefresh: { other: \"Refresh\" }\n\nID: { other: \"ID\" }\nCreated_At: { other: \"Created At\" }\nLink: { other: \"Link\" }\nCopy: { other: \"Copy\" }\nLink_copied: { other: \"Link copied to clipboard\" }\nPassword_copied: { other: \"Password copied to clipboard\" }\n\nActions: { other: \"Actions\" }\nAdd: { other: \"Add\" }\nUpdate: { other: \"Update\" }\nDelete: { other: \"Delete\" }\nYour_Passwords: { other: \"Your Passwords\" }\n\nCreate_Password: { other: \"Create Password\" }\nPassword: { other: \"Password\" }\nLength: { other: \"Length\" }\nExclude: { other: \"Exclude\" }\nExclude_chars: { other: \"Exclude chars\" }\nGenerate: { other: \"Generate\" }\nInvalid_length: { other: \"Invalid length\" }\nGeneration_error: { other: \"Generation error\" }\nGenerated_inserted: { other: \"Generated password inserted\" }\n\nWeak_password: { other: \"Weak password\" }\nStrong_password: { other: \"Strong password\" }\nChoose_stronger: { other: \"Please choose a stronger password\" }\nmissing: { other: \"missing\" }\nlength_8: { other: \"length ≥ 8\" }\ndigit: { other: \"digit\" }\nuppercase: { other: \"uppercase\" }\nlowercase: { other: \"lowercase\" }\nsymbol: { other: \"symbol\" }\n\nUpdate_Password: { other: \"Update Password\" }\nUpdated: { other: \"Updated\" }\nPassword_updated: { other: \"Password updated successfully\" }\n\nDelete_Password: { other: \"Delete Password\" }\nEnter_ID_to_delete: { other: \"Enter ID to delete\" }\nDeleted: { other: \"Deleted\" }\nDB_init_failed: { other: \"Database initialization error\" }\nPassword_deleted: { other: \"Password deleted successfully\" }"),
}
var resourceBeYaml = &fyne.StaticResource{
	StaticName: "be.yaml",
	StaticContent: []byte(
		"Password_Manager: { other: \"Менеджар пароляў\" }\nUnlock_Password_Manager: { other: \"Разблакіраваць менеджар пароляў\" }\nEnter_master_password: { other: \"Увядзіце майстар-пароль\" }\ninvalid_master_password: { other: \"Няправільны майстар-пароль\" }\nCreate_Master_Password: { other: \"Стварыць майстар-пароль\" }\nEnter_your_email: { other: \"Увядзіце ваш email\" }\nConfirm_master_password: { other: \"Пацвердзіце майстар-пароль\" }\nSave: { other: \"Захаваць\" }\nSuccess: { other: \"Поспех\" }\nMaster_password_saved: { other: \"Майстар-пароль захаваны\" }\npasswords_do_not_match: { other: \"Паролі не супадаюць\" }\nemail_and_password_required: { other: \"Патрабуюцца email і пароль\" }\nFirst-time_setup: { other: \"Першасная наладка\" }\n\nSession_locked: { other: \"Сесія заблакіравана праз бяздзейнасць\" }\nMaster_Password: { other: \"Майстар-пароль\" }\nUnlock_Session: { other: \"Разблакіраваць сесію\" }\nUnlock: { other: \"Разблакіраваць\" }\nExit: { other: \"Выйсці\" }\n\nShow_Filters: { other: \"Паказаць фільтры\" }\nService: { other: \"Сэрвіс\" }\nUsername: { other: \"Імя карыстальніка\" }\nCategory: { other: \"Катэгорыя\" }\nApply: { other: \"Ужыць\" }\nFilter_Passwords: { other: \"Фільтр пароляў\" }\nClose: { other: \"Закрыць\" }\nRefresh: { other: \"Абнавіць\" }\n\nID: { other: \"ID\" }\nCreated_At: { other: \"Створана\" }\nLink: { other: \"Спасылка\" }\nCopy: { other: \"Капіраваць\" }\nLink_copied: { other: \"Спасылка скапіравана ў буфер абмену\" }\nPassword_copied: { other: \"Пароль скапіраваны ў буфер абмену\" }\n\nActions: { other: \"Дзеянні\" }\nAdd: { other: \"Дадаць\" }\nUpdate: { other: \"Абнавіць\" }\nDelete: { other: \"Выдаліць\" }\nYour_Passwords: { other: \"Вашы паролі\" }\n\nCreate_Password: { other: \"Стварыць пароль\" }\nPassword: { other: \"Пароль\" }\nLength: { other: \"Даўжыня\" }\nExclude: { other: \"Выключыць\" }\nExclude_chars: { other: \"Выключыць сімвалы\" }\nGenerate: { other: \"Згенераваць\" }\nInvalid_length: { other: \"Некарэктная даўжыня\" }\nGeneration_error: { other: \"Памылка генерацыі\" }\nGenerated_inserted: { other: \"Згенераваны пароль устаўлены\" }\n\nWeak_password: { other: \"Слабы пароль\" }\nStrong_password: { other: \"Моцны пароль\" }\nChoose_stronger: { other: \"Калі ласка, абярыце больш моцны пароль\" }\nmissing: { other: \"ня хапае\" }\nlength_8: { other: \"даўжыня ≥ 8\" }\ndigit: { other: \"лічба\" }\nuppercase: { other: \"вялікая літара\" }\nlowercase: { other: \"малая літара\" }\nsymbol: { other: \"сімвал\" }\n\nUpdate_Password: { other: \"Абнавіць пароль\" }\nUpdated: { other: \"Абноўлена\" }\nPassword_updated: { other: \"Пароль паспяхова абноўлены\" }\n\nDelete_Password: { other: \"Выдаліць пароль\" }\nDB_init_failed: { other: \"Памылка ініцыялізацыі базы даных\" }\nEnter_ID_to_delete: { other: \"Увядзіце ID для выдалення\" }\nDeleted: { other: \"Выдалена\" }\nPassword_deleted: { other: \"Пароль паспяхова выдалены\" }"),
}
